import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ backgroundColor: "white", padding: "10px", boxShadow: "0px 2px 5px gray" }}>
          <h1 style={{ color: "black" }}>Next.js Lab</h1>
        </div>
        {children}
        </body>
    </html>
  );
}
